---
# Serverless Website Template
# ---------------------------
# 
# This CloudFormation template will deploy the following resources:
#   * S3 bucket configured to host static web content
#   * IAM user with access to the bucket
#   * CloudFront Distribution

AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CLI Login Serverless Website


# Parameters
# ----------
#
# These are the input parameters for this template. All of these parameters
# must be supplied for this template to be deployed.
Parameters:
  SiteName:
    Type: String
    Description: The DNS name of the website (no spaces). This will be the bucket name also.
    AllowedPattern: "(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)"
    ConstraintDescription: Must be a valid character in a DNS name.

  CertificateARN:
    Type: String
    Description: The ARN of the AWS Certificate Manager certificate to use. (Only required for HTTPS Websites)

# Metadata
# --------
#
# Metadata is mostly for organizing and presenting Parameters in a better way
# when using CloudFormation in the AWS Web UI.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Website Configuration
      Parameters:
      - SiteName
      - CertificateARN
    ParameterLabels:
      SiteName:
        default: "Site Name"
      CertificateARN:
        default: 'SSL Certificate'


Resources:
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SiteName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # #### S3 Bucket Policy
  #
  # Sets the required policy on the S3 bucket to allow web hosting.
  S3BucketPublicPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3WebsiteBucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${S3WebsiteBucket}/*"
          Principal: "*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref SiteName
        Origins:
        - DomainName: !Sub "${S3WebsiteBucket}.s3.amazonaws.com"
          Id: !Sub "S3-${S3WebsiteBucket}"
          S3OriginConfig:
            OriginAccessIdentity: ""
        Enabled: true
        Comment: !Sub "CloudFront Distribution for ${SiteName}"
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: "/index.html"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3-${S3WebsiteBucket}"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
        HttpVersion: http2
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

Outputs:
  WebsiteURL:
    Value: !Sub "https://${SiteName}/"
  BucketName:
    Value: !Ref S3WebsiteBucket
  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
  CloudFrontARN:
    Value: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
  CloudFrontDNS:
    Value: !GetAtt CloudFrontDistribution.DomainName
